# Generated by Django 3.2.12 on 2023-07-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_booking_travel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='booking',
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='classtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='classtype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contactnumber',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactnumber',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='station',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='station',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='train',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='train',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default=0, max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.DeleteModel(
            name='BookingDetail',
        ),
    ]
