# Generated by Django 3.2.12 on 2023-07-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='passenger',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
